name: Check





on: push





jobs:

  build:
    name: Check
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - run: npm install --no-save
        env:
          ADBLOCK: true
          DISABLE_OPENCOLLECTIVE: true
          HUSKY_SKIP_INSTALL: true

      - run: npm run test -- --verbose

      - run: npm run build

      - run: ls -lh dist/{index,bin}*

      - run: npm run bundle

      - run: ls -lh dist/{index,bin}*

      - uses: codecov/codecov-action@v1.0.7
        timeout-minutes: 1

