name: Gource Action

on: push

jobs:
  action:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nbprojekt/gource-action@v1
        with:
          gource_title: 'wabble'
          gource_resolution: '1440p'
          gource_fps: 60
          gource_filename_time: 10
          gource_font_size: 80
          gource_time_scale: 0.5
          gource_user_scale: 0.8
          gource_dir_depth: 5

      - uses: actions/upload-artifact@v2
        with:
          name: gource
          path: ./gource/gource.mp4
